import patterns
from pprint import pprint

rows = [
    {
        "Avg. Fill": "2164.00",
        "Cxl": "",
        "Edit": "",
        "Filled": "1",
        "Message": "",
        "Order #": "669465174",
        "Order PX": "2164.00",
        "Qty": "1",
        "Remain": "0",
        "Sent Time": "13:45 Jul 26",
        "Side": "Buy",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Limit",
        "Updated": "14:41 Jul 26"
    },
    {
        "Avg. Fill": "2167.00",
        "Cxl": "",
        "Edit": "",
        "Filled": "2",
        "Message": "",
        "Order #": "669425095",
        "Order PX": "",
        "Qty": "2",
        "Remain": "0",
        "Sent Time": "13:46 Jul 26",
        "Side": "Buy",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Market",
        "Updated": "13:46 Jul 26"
    },
    {
        "Avg. Fill": "2167.00",
        "Cxl": "",
        "Edit": "",
        "Filled": "1",
        "Message": "",
        "Order #": "669465173",
        "Order PX": "",
        "Qty": "1",
        "Remain": "0",
        "Sent Time": "13:45 Jul 26",
        "Side": "Sell",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Market",
        "Updated": "13:45 Jul 26"
    },
    {
        "Avg. Fill": "2165.00",
        "Cxl": "",
        "Edit": "",
        "Filled": "1",
        "Message": "The order was in a state that prohibited a cancel request",
        "Order #": "669434005",
        "Order PX": "2165.00",
        "Qty": "1",
        "Remain": "0",
        "Sent Time": "13:29 Jul 26",
        "Side": "Sell",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Limit",
        "Updated": "13:41 Jul 26"
    },
    {
        "Avg. Fill": "2165.00",
        "Cxl": "",
        "Edit": "",
        "Filled": "1",
        "Message": "The order was in a state that prohibited a cancel request",
        "Order #": "669404653",
        "Order PX": "2165.00",
        "Qty": "1",
        "Remain": "0",
        "Sent Time": "13:29 Jul 26",
        "Side": "Sell",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Limit",
        "Updated": "13:41 Jul 26"
    },
    {
        "Avg. Fill": "2165.25",
        "Cxl": "",
        "Edit": "",
        "Filled": "2",
        "Message": "",
        "Order #": "669414991",
        "Order PX": "",
        "Qty": "2",
        "Remain": "0",
        "Sent Time": "13:40 Jul 26",
        "Side": "Sell",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Market",
        "Updated": "13:40 Jul 26"
    },
    {
        "Avg. Fill": "2161.75",
        "Cxl": "",
        "Edit": "",
        "Filled": "1",
        "Message": "",
        "Order #": "669404652",
        "Order PX": "",
        "Qty": "1",
        "Remain": "0",
        "Sent Time": "13:29 Jul 26",
        "Side": "Buy",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Market",
        "Updated": "13:29 Jul 26"
    },
    {
        "Avg. Fill": "2161.75",
        "Cxl": "",
        "Edit": "",
        "Filled": "1",
        "Message": "",
        "Order #": "669434004",
        "Order PX": "",
        "Qty": "1",
        "Remain": "0",
        "Sent Time": "13:29 Jul 26",
        "Side": "Buy",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Market",
        "Updated": "13:29 Jul 26"
    },
    {
        "Avg. Fill": "2160.25",
        "Cxl": "",
        "Edit": "",
        "Filled": "1",
        "Message": "",
        "Order #": "669417272",
        "Order PX": "",
        "Qty": "1",
        "Remain": "0",
        "Sent Time": "0:26 Jul 26",
        "Side": "Sell",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Market",
        "Updated": "0:26 Jul 26"
    },
    {
        "Avg. Fill": "2160.50",
        "Cxl": "",
        "Edit": "",
        "Filled": "1",
        "Message": "",
        "Order #": "669397511",
        "Order PX": "",
        "Qty": "1",
        "Remain": "0",
        "Sent Time": "0:26 Jul 26",
        "Side": "Buy",
        "Status": "Filled",
        "Symbol": "EPU6",
        "TIF": "DAY",
        "Type": "Market",
        "Updated": "0:26 Jul 26"
    }
]

trades = patterns.assembleTrades(rows)
pprint(trades)
